### ISSUE TITLE
Fluentd keeps Windows k8s pods from shutting down

### ISSUE THREAD

**Issue by dotsuber** [fluent/fluentd#3340]
**Describe the bug**
I'm using Fluentd version 1.11.2 in EKS in Windows VMs. Sometimes pods get stuck in "terminating" status for hours and days, until I restart the VM. I checked the kubelet and the docker logs, and it seems like a log file which refuses to delete. Once I delete the Fluentd pod, the terminating pod succeed to delete. In my opinion, the root cause is the Fluentd which lock the file.
Here is a thread [HERE](https://github.com/fluent/fluent-bit/issues/2027) which describes the same problem in Fluent-bit, and the last comment says it solved in the latest version.

**To Reproduce**
I didn't succeed to reproduce the bug, it just happen to me once in few days.

**Expected behavior**
I expect to have some fix in Fluentd like they did in Fluent-bit, which fixes the lock on files.

**Your Environment**

- Fluentd version: 1.11.2
- Operating system: Windows server 2019

**Your Configuration**

```
<source>
  @type tail
  @log_level info
  path /var/log/containers/*.log
  exclude_path ["/var/log/containers/log-tailer-*", "/var/log/containers/geneva-logger-*"]
  pos_file /var/log/fluentd-docker.pos
  tag kubernetes.*
  format json
  time_key time
  time_format %Y-%m-%dT%H:%M:%S
  read_from_head true
</source>

# Don't care about fluentd logs
<match **fluentd**.log>
  @type null
</match>

<filter kubernetes.var.log.containers.**>
  @type kubernetes_metadata
</filter>

<match kubernetes.var.log.containers.**>
  @type rewrite_tag_filter
  # <rule>
  #   key log
  #   pattern .+
  #   tag kubernetes.prod
  # </rule>
  <rule>
    key $['kubernetes']['namespace_name']
    pattern ^(.+)$
    tag kubernetes.$1
  </rule>
</match>

<match kubernetes.**>
  @type forward
  require_ack_response true
  expire_dns_cache 300
  <buffer>
    @type file
    path /var/log/td-agent/buffer/kubernetes.{{ .Values.geneva.chartNamespace }}
    chunk_limit_size 4m
    queued_chunks_limit_size 4096
    flush_interval 10s
    flush_thread_count 8
    retry_max_times 8
    retry_timeout 5m
  </buffer>
  <server>
    host {{ printf "%s.%s.svc.cluster.local" .Values.geneva.service.name .Values.geneva.chartNamespace }}
    port {{ .Values.geneva.fluentd.port }}
  </server>
{{- if .Values.certificate }}
  transport tls
  tls_cert_path C:\tmp\fluentd\secrets\fluentd-cert.pem
  tls_allow_self_signed_cert true
  tls_version TLSv1_2
{{- end }}
</match>

```
```
E0325 00:32:14.667270 4400 remote_runtime.go:261] RemoveContainer "cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d" from runtime service failed: rpc error: code = Unknown desc = failed to remove container "cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d": Error response from daem
on: unable to remove filesystem for cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d: CreateFile C:\ProgramData\docker\containers\cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d\cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d-json.log: Access is denied.

```

**Additional context**
Is there any update or fix for that problem like in Fluent-bit?

**Comment by fujimotos** [comment]
> Once I delete the Fluentd pod, the terminating pod succeed to delete. In my opinion, the root cause is the Fluentd which lock the file.
> Here is a thread HERE which describes the same problem in Fluent-bit, and the last comment says it solved in the latest version.

@dotsuber  I fixed this bug for Fluent Bit last year. Basically, the bug was that k8s
was waiting for Windows to remove a file, and Windows, in turn, was waiting for
Fluent Bit to close its handler.

The fix was to teach Fluent Bit about `DeletePending`. It is Win32-specific flag that
basically says "This file is to be deleted. Please close handlers ASAP".  As I recall,
Fluent Bit (before v1.4.3) was ignoring this flag.

Probably we need to teach the same thing to Fluentd as well. I'll find some time to
look at a relevant code in Fluentd to investigate the issue.

**Comment by fmad** [comment]
We had this happen to us as well and the way we worked around it was by using
`open_on_every_update true` - not ideal, but useful as a workaround to stop us from having so much pain with deployments.

**Comment by dotsuber** [comment]
> > Once I delete the Fluentd pod, the terminating pod succeed to delete. In my opinion, the root cause is the Fluentd which lock the file.
> > Here is a thread HERE which describes the same problem in Fluent-bit, and the last comment says it solved in the latest version.
> 
> @dotsuber I fixed this bug for Fluent Bit last year. Basically, the bug was that k8s
> was waiting for Windows to remove a file, and Windows, in turn, was waiting for
> Fluent Bit to close its handler.
> 
> The fix was to teach Fluent Bit about `DeletePending`. It is Win32-specific flag that
> basically says "This file is to be deleted. Please close handlers ASAP". As I recall,
> Fluent Bit (before v1.4.3) was ignoring this flag.
> 
> Probably we need to teach the same thing to Fluentd as well. I'll find some time to
> look at a relevant code in Fluentd to investigate the issue.

Hi, thanks for your comment! Do you have some ETA for the fix?

**Comment by AmeerAssi** [comment]
@fujimotos the issue mentioned doesn't look related to this issue.
look here: https://github.com/fluent/fluentd/issues/3365
the issue you mentioned is reproducible only on v1.12.x, and the used version for this issue is v1.11.2.

today the issue is reproducing in daily basis, do you need extra information to investigate it?

**Comment by AmeerAssi** [comment]
@fujimotos we upgraded to version v1.12.4, and the issue is still happening.
any suggestion how to proceed?

**Comment by fujimotos** [comment]
@AmeerAssi We need to find out which file is being open. Can you enable the
file tracking on your WIndows machine (need restart):

    % openfile local off

and execute the following on stacked instance?

    % openfile query

This should show the list of all files currently open. So we should be able
to dtermine which file is preventing Windows from shutdown.

**Comment by AmeerAssi** [comment]
thanks @fujimotos 
don't you think that the file mentioned initially in the issue description is the one preventing windows from shutdown:

> E0325 00:32:14.667270 4400 remote_runtime.go:261] RemoveContainer "cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d" from runtime service failed: rpc error: code = Unknown desc = failed to remove container "cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d": Error response from daem
on: unable to remove filesystem for cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d: CreateFile **C:\ProgramData\docker\containers\cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d\cdce17ef7168b13b58d9409524324d0067f46a554979cfea0db7f6a2fcc0627d-json.log: Access is denied.**

**Comment by AmeerAssi** [comment]
@fujimotos I hope this information would help continue investigating this issue.

see attached fluentd log file when the issue reproduced.
[fluentdlogs.txt](https://github.com/fluent/fluentd/files/6712205/fluentdlogs.txt)

when checking describe pod, we can see its stuck on the same file was under rotation in the last fluentd log:

Pod Describe info stuck info:
`    State:          Terminated
      Reason:       Error
      Message:      unable to remove filesystem for b96bf269e42d12f71d475384b68c7aa88d4530e5d5ab9690305e4e6384fb893c: CreateFile C:\ProgramData\docker\containers\b96bf269e42d12f71d475384b68c7aa88d4530e5d5ab9690305e4e6384fb893c\**b96bf269e42d12f71d475384b68c7aa88d4530e5d5ab9690305e4e6384fb893c**-json.log: Access is denied.
      Exit Code:    -1073741510
      Started:      Thu, 24 Jun 2021 22:45:43 +0300
      Finished:     Thu, 24 Jun 2021 22:58:35 +0300`


last line on the fluentd log:
2021-06-24 19:58:35 +0000 [info]: #0 detected rotation of /var/log/containers/data-scan-74db9447-bp9d9_data-scan7bb09985-0751-490b-8d7d-0f52f3c4c5f3_data-scan-**b96bf269e42d12f71d475384b68c7aa88d4530e5d5ab9690305e4e6384fb893c**.log; waiting 5 seconds


what do you suggest as a next step? as I am afraid that I don't have access to the machine reproducing the issue, as its happening in production environment, and its reproducing once in several days which is not easy to reproduce locally.

**Comment by fujimotos** [comment]
@AmeerAssi Sorry for a delayed response. I submit a patch  #3457
that probably fixes your issue.

Can you check that version out and see if it actually works?

**Comment by AmeerAssi** [comment]
thanks @fujimotos 
could you please create a release with the last merged fix, so I can test it?
Also, does the DeletePending enabled by default, or should I add some configuration once I test?

**Comment by fujimotos** [comment]
@AmeerAssi That patch has been merged into master and will be included
in th next release (probably it will be published within a month) .

Reopen this issue if you can reproduce the same issue with the new release.

**Comment by lizhuqi** [comment]
Will the fix be in next fluent-bit release as well?

**Comment by lizhuqi** [comment]
fluent-bit locks file error still happens for fluent-bit 1.17.7

**Comment by lizhuqi** [comment]
@fujimotos v1.13.3 is out. Is this fix in v1.13.3?

**Comment by fujimotos** [comment]
@lizhuqi Yes.
