### ISSUE TITLE
Fluentd 1.15 breaks readonlyRootFilesystem with fluentd_lock directory. Need configurable lock directory.

### ISSUE THREAD

**Issue by aggarwalShivani** [fluent/fluentd#3924]
### Describe the bug

Hi, 
I'm upgrading td-agent from v4.3.2 to v4.4.1.
The td-agent rpm is taken and installed on a centos7 docker image and fluentd image runs as pods in kubernetes env.
One major req is - all containers run with securityContext.readonlyrootFilesystem enabled. 
Ref: https://kubesec.io/basics/containers-securitycontext-readonlyrootfilesystem-true/

With this, on runtime, the filesystem of the img is immutable unless the locations are volume-mounts. This has been working fine for us for a while (from many td-agent releases).
But with fluentd gem 1.15.1 update: 
https://www.fluentd.org/blog/fluentd-v1.15.1-has-been-released
https://github.com/fluent/fluentd/pull/3808/files - this change in particular creates files under /fluentd-lock-<suffix> on run-time.

As readonlyRootFilesystem is enabled, this is immuntable filesystem and so fluentd startup fails with this error:
`Unexpected error Read-only file system @ dir_s_mkdir - /fluentd-lock-20221020-6-1t5muy4`

To address this, we can configure this as an emptydir volume mount at the k8s/helm level so the filesystem location becomes writable for the fluentd process. But today, the file path keeps changing - /fluentd-lock-<changeable-suffix> and so cannot be configured as volume mounts.

The question is - can the location of fluentd lock directory be made configurable?
For ex. can we configure fluentd to use /tmp/fluentd-lock-<changeable-suffix> as the lock directory?
If possible, pls let us know how.

If not possible yet in existing fluentd, this change is definitely needed as atleast with this, we can control the path to be writable and resolve this issue.

### To Reproduce

1. Deploy fluentd (td agent 4.4.1) as a docker container or pod. 
2. Container's securityContext must have readonlyRootFilesystem enabled
        securityContext:
          readOnlyRootFilesystem: true

3. Start fluentd container 

### Expected behavior

Fluentd should work with readonlyRootFilesystem enabled too. 
In case the files are needed to be created for lock files, there should be an option to modify the LOCK directory i.e. its path should be user-configurable.

### Your Environment

```markdown
- Fluentd version: 1.15.2
- TD Agent version: 4.4.1
- Operating system: Centos7
```

### Your Configuration

```apache
<source>
  @type tail
  path /var/log/containers/*.log
  read_from_head true
  pos_file /var/log/fluentd-container-log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag kubernetes.*
  format json
</source>
<filter kubernetes.**>
  @type kubernetes_metadata
  kubernetes_url https://kubernetes.default.svc:443
</filter>

<match **>
  @type opensearch
  @log_level info
  include_tag_key true
  host opensearch
  port 9200
  logstash_format true
  reload_connections false
  reconnect_on_error true
  reload_on_failure true
  request_timeout 10s
  <buffer>
    @type file
    chunk_limit_size 8MB
    path /var/log/td-agent/fluentd-buffer/buffer.logging.all
    total_limit_size 1024m
  </buffer>
</match>
```

### Your Error Log

```shell
022-10-20 12:49:43 +0000 [info]: starting fluentd-1.15.2 pid=6 ruby="2.7.6"
2022-10-20 12:49:43 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--under-supervisor"]
Unexpected error Read-only file system @ dir_s_mkdir - /fluentd-lock-20221020-6-1t5muy4
  /opt/td-agent/lib/ruby/2.7.0/tmpdir.rb:85:in `mkdir'
  /opt/td-agent/lib/ruby/2.7.0/tmpdir.rb:85:in `block in mktmpdir'
  /opt/td-agent/lib/ruby/2.7.0/tmpdir.rb:129:in `create'
  /opt/td-agent/lib/ruby/2.7.0/tmpdir.rb:83:in `mktmpdir'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:47:in `before_run'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.3.0/lib/serverengine/server.rb:125:in `main'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.3.0/lib/serverengine/daemon.rb:119:in `main'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.3.0/lib/serverengine/daemon.rb:68:in `run'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:883:in `supervise'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:723:in `run_supervisor'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/bin/fluentd:15:in `<top (required)>'
  /opt/td-agent/bin/fluentd:23:in `load'
  /opt/td-agent/bin/fluentd:23:in `<top (required)>'
  /usr/sbin/td-agent:21:in `load'
  /usr/sbin/td-agent:21:in `<main>'
```

**Comment by fujimotos** [comment]
> The question is - can the location of fluentd lock directory be made configurable?
> For ex. can we configure fluentd to use /tmp/fluentd-lock- as the lock directory?
> If possible, pls let us know how.

@aggarwalShivani Yes. Fluentd relies on Ruby's [mktmpdir](https://docs.ruby-lang.org/ja/latest/method/Dir/s/mktmpdir.html) to get a temporary path,
so you just need to do:

 1. Prepare some directory that Fluentd can write. 
 2. Set the environment variable `TMPDIR` to that path
    * e.g. `docker run --env TMPDIR=/tmp/fluentd/`

This should resolve the error you encountered.

_Technical Note:_ Fluentd generally assumes that `tmpdir` (and hence `tempfile`)
returns a safely writiable path.

This is (and has been) an implicit assumption. Here are some examples:

* https://github.com/fluent/fluentd/blob/v1.15.2/lib/fluent/plugin/buffer/chunk.rb#L209
* https://github.com/fluent/fluentd/blob/v1.15.2/lib/fluent/plugin/out_exec.rb#L74

So preparing a writable directory as described above is highly recommended.

**Comment by aggarwalShivani** [comment]
Thanks @fujimotos for the pointers.
I tried the same, but its still not working

Env TMPDIR is set for the container like TMPDIR=/tmp-fluentd
This directory is a volume-mount in the pod - and it is writable. But the process is still trying to create lock files at /fluentd-lock only. Any ideas on what could be wrong?
What more has to be configured apart from setting the env?

```
2022-10-21 15:02:05 +0000 [info]: starting fluentd-1.15.2 pid=6 ruby="2.7.6"
2022-10-21 15:02:05 +0000 [info]: spawn command to main:  cmdline=["/opt/td-agent/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/td-agent", "--under-supervisor"]
Unexpected error Read-only file system @ dir_s_mkdir - /fluentd-lock-20221021-6-yii6xc
  /opt/td-agent/lib/ruby/2.7.0/tmpdir.rb:85:in `mkdir'
  /opt/td-agent/lib/ruby/2.7.0/tmpdir.rb:85:in `block in mktmpdir'
  /opt/td-agent/lib/ruby/2.7.0/tmpdir.rb:129:in `create'
  /opt/td-agent/lib/ruby/2.7.0/tmpdir.rb:83:in `mktmpdir'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:47:in `before_run'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.3.0/lib/serverengine/server.rb:125:in `main'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.3.0/lib/serverengine/daemon.rb:119:in `main'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.3.0/lib/serverengine/daemon.rb:68:in `run'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:883:in `supervise'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:723:in `run_supervisor'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/bin/fluentd:15:in `<top (required)>'
  /opt/td-agent/bin/fluentd:23:in `load'
  /opt/td-agent/bin/fluentd:23:in `<top (required)>'
  /usr/sbin/td-agent:21:in `load'
  /usr/sbin/td-agent:21:in `<main>'
```

**Comment by fujimotos** [comment]
The probability is that your env was not passed to td-agent properly. 

https://github.com/ruby/tmpdir/blob/master/lib/tmpdir.rb#L23-L39

Here is how Ruby determines the temporary directory. It essentially iterate
a set of envs (such as TMPDIR and TMP) and return the first directory
it could found.

The exact steps largely depends on how you set up the container,
but here is the most common steps:

* If you installed td-agent package and use systemd to manage the daemon,
   you'll need to add an entry to ` /etc/sysconfig/td-agent` (RHEL-family) or `/etc/default/td-agent` (Debian-family).

* If you use the stock Fluentd Docker imgage, adding `--env` would enough.

I can confirm that Fluentd will use the directory on my dev machine,
so make sure that the env is passed to your Fluentd process.

**Comment by vijeyanidhi** [comment]
@fujimotos 
A similar problem.

I have set the env value in the docker file with `ENV TMPDIR=/tmp/fluentd/`
And in docker entry point I am able to see the value passed.
```
echo "Testing output"
echo ${TMPDIR}
exec fluentd -c /fluentd/etc/${FLUENTD_CONF} -p /fluentd/plugins ${FLUENTD_OPT}
```

output logs:
```
Testing output
/tmp/fluentd/
2022-10-31 05:32:54 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluentd.conf"
2022-10-31 05:32:54 +0000 [info]: gem 'fluentd' version '1.15.2'
2022-10-31 05:32:54 +0000 [info]: gem 'fluent-plugin-concat' version '2.5.0'
2022-10-31 05:32:54 +0000 [info]: gem 'fluent-plugin-kafka' version '0.17.5'
2022-10-31 05:32:54 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '3.1.0'
2022-10-31 05:32:54 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2022-10-31 05:32:54 +0000 [info]: gem 'fluent-plugin-newrelic' version '1.2.1'
2022-10-31 05:32:54 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.3'
2022-10-31 05:32:54 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'

<Redacted>

2022-10-31 05:32:55 +0000 [info]: starting fluentd-1.15.2 pid=1 ruby="3.0.4"
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
. is not writable: /
Unexpected error could not find a temporary directory
  /usr/share/ruby/tmpdir.rb:39:in `tmpdir'
  /usr/share/ruby/tmpdir.rb:115:in `tmpdir'
  /usr/share/ruby/tmpdir.rb:130:in `create'
  /usr/share/ruby/tmpdir.rb:90:in `mktmpdir'
  /usr/share/gems/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:47:in `before_run'
  /usr/share/gems/gems/serverengine-2.3.0/lib/serverengine/server.rb:125:in `main'
  /usr/share/gems/gems/serverengine-2.3.0/lib/serverengine/daemon.rb:119:in `main'
  /usr/share/gems/gems/serverengine-2.3.0/lib/serverengine/daemon.rb:68:in `run'
  /usr/share/gems/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:883:in `supervise'
  /usr/share/gems/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:723:in `run_supervisor'
  /usr/share/gems/gems/fluentd-1.15.2/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
  <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
  /usr/share/gems/gems/fluentd-1.15.2/bin/fluentd:15:in `<top (required)>'
  /usr/bin/fluentd:25:in `load'
  /usr/bin/fluentd:25:in `<main>'
2022-10-31 05:32:55 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/bin/fluentd", "-c", "/fluentd/etc/fluentd.conf", "-p", "/fluentd/plugins", "--under-supervisor"]

```

Can you provide any more info on how to `make sure that the env is passed to your Fluentd process.`?

**Comment by vijeyanidhi** [comment]
It worked.
Previously it was working fine without setting up the permissions and since we did not set any permission for the directory it did not strike.

Thanks for the help 
@fujimotos
